#!/usr/bin/env ruby
require_relative 'world'
require_relative 'robot'

world = World.new
robot = Robot.new(world)

print "Enter a command (PLACE, MOVE, LEFT, RIGHT or REPORT): "
$stdout.flush

ARGF.each do |line|
  array = line.chomp.split(' ')
  if command = array[0]
    if array[1]
      options = array[1].split(',')
    end

    break if line.chomp=='exit'
    if false == robot.send(command.downcase, *options)
      puts "Invalid command."
    end
    print "Enter a command (PLACE, MOVE, LEFT, RIGHT or REPORT): "
    $stdout.flush
  end
end
