#!/usr/bin/env ruby
require_relative 'world'
require_relative 'robot'

world = World.new
robot = Robot.new(world)

def prompt_input
  if ARGF.file.class==IO
    print "Enter a command (PLACE, MOVE, LEFT, RIGHT or REPORT): "
    $stdout.flush
  end
end

prompt_input

ARGF.each do |line|
  array = line.downcase.chomp.split(' ')
  if command = array[0]
    if array[1]
      options = array[1].split(',')
    end

    break if command=='exit'

    result, message = robot.send(command.downcase, *options)
    if result==false
      puts "Invalid command."
    end
    if message
      puts message
    end
    prompt_input
  end
end


